######################################################################
# Automatically generated by qmake (2.01a) Sa. Sep 16 08:48:23 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . doc examples src
INCLUDEPATH += . src

# Input
HEADERS += doc/mainpage.h src/ladspa++.h
SOURCES += examples/amplifier.cpp
OTHER_FILES += README.md

